import dotenv from "dotenv";
import crypto from "crypto";

// Ensure environment variables are loaded
dotenv.config();

// Determine environments
const NODE_ENV = process.env.NODE_ENV || "development";
const PORT = parseInt(process.env.PORT || "3000", 10);
const APP_URL = process.env.APP_URL || "";
const isProduction = NODE_ENV === "production";
const isAIStudioPreview = APP_URL.includes("ais-dev-") || APP_URL.includes("ais-pre-") || APP_URL.includes("run.app");

// 1. JWT_SECRET Validation & Auto-generation
let jwtSecret = process.env.JWT_SECRET || "";

if (!jwtSecret) {
  if (isProduction && !isAIStudioPreview) {
    throw new Error("JWT_SECRET is required in production.");
  } else {
    // Generate a secure 32-byte key automatically using the crypto module
    const autoSecret = crypto.randomBytes(32).toString("hex");
    jwtSecret = autoSecret;
    process.env.JWT_SECRET = autoSecret;

    if (isProduction) {
      console.warn("================================================================================");
      console.warn("⚠️  [SECURITY WARNING] JWT_SECRET is not configured in production (AI Studio Preview).");
      console.warn("   A cryptographically secure 32-byte key has been generated automatically for this preview session.");
      console.warn("   For optimal security and persistence of user sessions across container restarts,");
      console.warn("   please configure the JWT_SECRET variable in your Secrets/Settings panel.");
      console.warn("================================================================================");
    } else {
      console.warn("================================================================================");
      console.warn("⚠️  [WARNING] JWT_SECRET is not configured.");
      console.warn("   A cryptographically secure 32-byte key has been generated automatically for development.");
      console.warn("   This key is being used for the current session execution.");
      console.warn("   In a production environment, the server will refuse to start without JWT_SECRET.");
      console.warn("================================================================================");
    }
  }
}

// Validation of key safety
if (jwtSecret.length < 32) {
  throw new Error("JWT_SECRET must contain at least 32 characters.");
}

if (!/^[a-fA-F0-9]{64}$/.test(jwtSecret)) {
  console.warn("⚠️  [WARNING] JWT_SECRET is not a 256-bit hexadecimal key. It is recommended to use a 64-character hex string (e.g. generated by crypto.randomBytes(32)) for optimal security.");
}

// 2. DATABASE_URL / SQL Credentials Validation
const SQL_HOST = process.env.SQL_HOST || "";
const SQL_USER = process.env.SQL_USER || "";
const SQL_PASSWORD = process.env.SQL_PASSWORD || "";
const SQL_DB_NAME = process.env.SQL_DB_NAME || "";
let DATABASE_URL = process.env.DATABASE_URL || "";

if (!DATABASE_URL && SQL_HOST) {
  DATABASE_URL = `postgres://${SQL_USER}:${SQL_PASSWORD}@${SQL_HOST}/${SQL_DB_NAME}`;
}

// Clean common copy-paste artifacts (e.g. keeping literal brackets [YOUR-PASSWORD] around the password)
if (DATABASE_URL && (DATABASE_URL.includes('[') || DATABASE_URL.includes(']'))) {
  try {
    const parts = DATABASE_URL.split('://');
    if (parts.length === 2) {
      const scheme = parts[0];
      const rest = parts[1];
      const atIdx = rest.indexOf('@');
      if (atIdx !== -1) {
        const auth = rest.substring(0, atIdx);
        const hostPath = rest.substring(atIdx + 1);
        const colonIdx = auth.indexOf(':');
        if (colonIdx !== -1) {
          const user = auth.substring(0, colonIdx);
          let pass = auth.substring(colonIdx + 1);
          if (pass.startsWith('[') && pass.endsWith(']')) {
            pass = pass.substring(1, pass.length - 1);
          }
          DATABASE_URL = `${scheme}://${user}:${encodeURIComponent(decodeURIComponent(pass))}@${hostPath}`;
        }
      }
    }
  } catch (e) {
    // Keep original
  }
}

if (isProduction && !isAIStudioPreview && !DATABASE_URL) {
  throw new Error("DATABASE_URL or SQL database credentials (SQL_HOST, etc.) are required in production.");
} else if (!DATABASE_URL) {
  console.warn("⚠️  [WARNING] DATABASE_URL or SQL credentials are not defined. Local/mock fallback might be used.");
}

// 3. GEMINI_API_KEY Validation
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";
if (!GEMINI_API_KEY || GEMINI_API_KEY === "MY_GEMINI_API_KEY") {
  console.warn("⚠️  [WARNING] GEMINI_API_KEY is not configured or uses placeholder. AI features will be disabled or degraded.");
}

// 4. SPOTIFY Credentials Validation
const SPOTIFY_CLIENT_ID = process.env.SPOTIFY_CLIENT_ID || "";
const SPOTIFY_CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET || "";

if (!SPOTIFY_CLIENT_ID || !SPOTIFY_CLIENT_SECRET) {
  console.info("ℹ️  [INFO] Spotify integration is not configured. (Optional SPOTIFY_CLIENT_ID & SPOTIFY_CLIENT_SECRET are missing)");
}

// Combined configuration object
export const config = Object.freeze({
  server: Object.freeze({
    env: NODE_ENV,
    port: PORT,
    appUrl: APP_URL,
    isProduction,
    isAIStudioPreview,
  }),
  jwt: Object.freeze({
    secret: jwtSecret,
  }),
  database: Object.freeze({
    url: DATABASE_URL,
    host: SQL_HOST,
    user: SQL_USER,
    password: SQL_PASSWORD,
    dbName: SQL_DB_NAME,
  }),
  gemini: Object.freeze({
    apiKey: GEMINI_API_KEY,
  }),
  spotify: Object.freeze({
    clientId: SPOTIFY_CLIENT_ID,
    clientSecret: SPOTIFY_CLIENT_SECRET,
  }),
});

export default config;
